### ISSUE TITLE
Confused of Extract Dataset

### ISSUE THREAD

**Issue by kkennethwu** [NagabhushanSN95/ViP-NeRF#4]
Hi, thanks for your great work. I have a problem about extract dataset of RealEstate10K. 
I ran `python VideoNameMapper.py`, `python SceneSelector01.py` successfully.
And when I ran `python DataExtractor01.py`, I got this error:

<img width="1076" alt="截圖 2023-08-11 下午2 18 48" src="https://github.com/NagabhushanSN95/ViP-NeRF/assets/71262989/e287388f-b310-492e-82e4-be006cfd0b42">

And I'm confused of what these three python file do. Below is the config in SceneSelector01.py and DataExtractor.py :
<img width="438" alt="截圖 2023-08-11 下午2 24 24" src="https://github.com/NagabhushanSN95/ViP-NeRF/assets/71262989/20370613-21ab-4d37-abd6-ae92936ff3ab">

<img width="801" alt="截圖 2023-08-11 下午2 25 58" src="https://github.com/NagabhushanSN95/ViP-NeRF/assets/71262989/36e651fe-f5bd-4730-8bef-c64ba8dbb87b">

**Comment by kkennethwu** [comment]
Also, if I modify the range to 10 in `data_extractor.extract_data(feature, range(500))`, I got this error.
<img width="1021" alt="截圖 2023-08-11 下午2 39 38" src="https://github.com/NagabhushanSN95/ViP-NeRF/assets/71262989/35d6bfa2-642e-4413-98f4-88d2296b4d92">

**Comment by NagabhushanSN95** [comment]
Hi, thanks for your interest in our work. The data extraction for RealEstate-10K is not configured properly yet. I will update this thread once that is done. It may take another month or so. However, the data extraction pipeline for the other datasets should work. 

If you want to experiment with RealEstate-10K dataset, you can follow the [guidelines on the RealEstate-10K dataset webpage](https://google.github.io/realestate10k/download.html) to download it. For any other datasets, you can follow a similar approach. Then place the files similar to how the LLFF/DTU datasets are placed and you should be good to go!

**Comment by NagabhushanSN95** [comment]
Please check [this documentation](https://github.com/NagabhushanSN95/ViP-NeRF/blob/main/src/database_utils/README.md#custom-databases) for an example of how to place the data.

Or, you can place the data however you prefer and modify the [data loader](https://github.com/NagabhushanSN95/ViP-NeRF/tree/main/src/data_loaders) appropriately

**Comment by kkennethwu** [comment]
I see ! big thanks for your help. I've tried nerf-llff successfully.

**Comment by NagabhushanSN95** [comment]
Closing this issue.
