### ISSUE TITLE
How to make my own dataset? 

### ISSUE THREAD

**Issue by JerryPW** [NagabhushanSN95/ViP-NeRF#5]
Hi! Thanks for your great work!!

However, I've been bothered by the procedure of making my own custom dataset. Could you provide some information about it? Thanks a lot! 

Hoping for your reply soon!

**Comment by NagabhushanSN95** [comment]
Hi, thanks for your interest in our work. I've outlined the procedure [here](https://github.com/NagabhushanSN95/ViP-NeRF/blob/main/src/database_utils/README.md#custom-databases). If you can specify your exact issue, maybe I can help better. Or if you have suggestions to make the README more descriptive, let me know.
